In [3]:
import numpy as np

In [5]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [11]:
np.array([1,2,3,4], dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [13]:
a1 = np.array([1,2,3,4])

In [15]:
type(a1)

numpy.ndarray

In [23]:
a2 = np.array([[1,2,3,4],[1,2,3,4]])


In [25]:
a2.shape

(2, 4)

In [27]:
a2.ndim

2

In [29]:
a2.dtype

dtype('int32')

In [31]:
a2.size

8

In [37]:
np.zeros([2,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [39]:
np.ones((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [51]:
np.full((3,5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [53]:
np.linspace(0,1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [63]:
np.random.seed(0)
np.random.random((3,3))

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [65]:
np.random.normal(0,1,(3,3))

array([[ 1.26611853, -0.50587654,  2.54520078],
       [ 1.08081191,  0.48431215,  0.57914048],
       [-0.18158257,  1.41020463, -0.37447169]])

In [67]:
np.random.randint(0,10, (4,5))

array([[0, 1, 9, 9, 0],
       [4, 7, 3, 2, 7],
       [2, 0, 0, 4, 5],
       [5, 6, 8, 4, 1]])

In [69]:
np.random.rand(4,4)

array([[0.94374808, 0.6818203 , 0.3595079 , 0.43703195],
       [0.6976312 , 0.06022547, 0.66676672, 0.67063787],
       [0.21038256, 0.1289263 , 0.31542835, 0.36371077],
       [0.57019677, 0.43860151, 0.98837384, 0.10204481]])